site_name: Hidku Security Playbook
theme:
  name: material

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
  - js/mermaid-init.js
